### ISSUE TITLE
Cipher method AES-128-CFB not available

### ISSUE THREAD

**Issue by 404found42** [Pixelfck/SymmetricEncryption#3]
the function 'openssl_get_cipher_methods' no longer returns the uppercase variants of the name.
So I suggest to modify "CIPHER_METHOD = 'AES-128-CFB';" 
to   "CIPHER_METHOD = 'aes-128-cfb';"

**Comment by Jacco-V** [comment]
Thanks for the heads up, I'll fix it.

**Comment by Pixelfck** [comment]
Thanks for the notification. I'll look into it asap.

**Comment by Pixelfck** [comment]
A fix has been published and [tagged as 2.0.2](https://github.com/Pixelfck/SymmetricEncryption/tree/2.0.2)
