### ISSUE TITLE
curly braces

### ISSUE THREAD

**Issue by Schoonmoeder** [Pixelfck/SymmetricEncryption#4]
hello,

i had an issue with the curly braces and after changing it to [ ] it worked.

https://github.com/Pixelfck/SymmetricEncryption/blob/c6f06a27691d226776d14e5e476ceb12b3c94c94/src/SymmetricEncryption.php#L241

**Comment by Pixelfck** [comment]
Fixed in version [2.0.3](/Pixelfck/SymmetricEncryption/tree/2.0.3).
